#!/usr/bin/env bash
set -euo pipefail

required_vars=(
  FIREBASE_API_KEY
  FIREBASE_APP_ID
  FIREBASE_MESSAGING_SENDER_ID
  FIREBASE_PROJECT_ID
  FIREBASE_STORAGE_BUCKET
)

for v in "${required_vars[@]}"; do
  if [ -z "${!v:-}" ]; then
    echo "Missing required env var: $v"
    echo "Tip: source .env.firebase.local"
    exit 1
  fi
done

flutter run -d chrome \
  --dart-define=FIREBASE_API_KEY="${FIREBASE_API_KEY}" \
  --dart-define=FIREBASE_APP_ID="${FIREBASE_APP_ID}" \
  --dart-define=FIREBASE_MESSAGING_SENDER_ID="${FIREBASE_MESSAGING_SENDER_ID}" \
  --dart-define=FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID}" \
  --dart-define=FIREBASE_STORAGE_BUCKET="${FIREBASE_STORAGE_BUCKET}" \
  ${FF_CHAT_ENABLED:+--dart-define=FF_CHAT_ENABLED=${FF_CHAT_ENABLED}} \
  ${FF_CHAT_ATTACHMENTS_ENABLED:+--dart-define=FF_CHAT_ATTACHMENTS_ENABLED=${FF_CHAT_ATTACHMENTS_ENABLED}} \
  ${FF_HEALTH_RECORD_SHARING_ENABLED:+--dart-define=FF_HEALTH_RECORD_SHARING_ENABLED=${FF_HEALTH_RECORD_SHARING_ENABLED}} \
  ${FF_APPOINTMENT_RESCHEDULE_ENABLED:+--dart-define=FF_APPOINTMENT_RESCHEDULE_ENABLED=${FF_APPOINTMENT_RESCHEDULE_ENABLED}} \
  ${FF_EMERGENCY_LOCATION_SHARE_ENABLED:+--dart-define=FF_EMERGENCY_LOCATION_SHARE_ENABLED=${FF_EMERGENCY_LOCATION_SHARE_ENABLED}} \
  ${FF_PROVIDER_REVIEWS_ENABLED:+--dart-define=FF_PROVIDER_REVIEWS_ENABLED=${FF_PROVIDER_REVIEWS_ENABLED}} \
  ${FF_AI_TRIAGE_ENABLED:+--dart-define=FF_AI_TRIAGE_ENABLED=${FF_AI_TRIAGE_ENABLED}} \
  ${FF_PAYMENTS_ENABLED:+--dart-define=FF_PAYMENTS_ENABLED=${FF_PAYMENTS_ENABLED}} \
  ${FF_ADMIN_CONSOLE_ENABLED:+--dart-define=FF_ADMIN_CONSOLE_ENABLED=${FF_ADMIN_CONSOLE_ENABLED}} \
  ${FF_MAPS_ENABLED:+--dart-define=FF_MAPS_ENABLED=${FF_MAPS_ENABLED}}
